# Generated by Django 6.0.2 on 2026-06-03 04:43

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('duration', models.PositiveIntegerField(help_text='In days')),
                ('distance', models.PositiveIntegerField(help_text='In kms')),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='trek_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('itinerary', tinymce.models.HTMLField()),
                ('map_embed_url', models.TextField(blank=True, help_text="Google My Maps 'Embed on my site' URL (only the src link inside the iframe)", null=True)),
            ],
            options={
                'verbose_name': 'Trek',
                'verbose_name_plural': 'Treks',
                'db_table': 'trek',
            },
        ),
    ]
