# Generated by Django 6.0.2 on 2026-06-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trek',
            name='featured',
            field=models.BooleanField(default=True),
        ),
    ]
